# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rny4I0dt415SvmJlk61YXMFn30FZy4fg
"""

x = 5
print (type(x))

y = 0.5
print (type(y))

z = "Hello World"
print(type(z))



for i in range(1):
  print (i)

j = 0
while j<10 :
  j = j + 1

total = 0
for i in range(2,6) :

lanjut = True
while(lanjut) :
  option = input("lanjut atau tidak ? (y/n)")
  if(option == 'n') :
    lanjut = False
    print ("program berhenti")

username = "smk"
password = "wikrama"
kesempatan = 3

while (kesempatan > 0):
  username_user = input("masukan username : ")
  password_user = input("masukan password : ")

  if(username == username_user and password == password_user):
    print("login berhasil")
    break
  else :
    kesempatan -= 1
    print("kesempatan tersisa {} kali lagi" . format(kesempatan))

def tambahHippo():
  hippos = 0
  answer = 'y'
  while answer == 'y' :
    hippos = hippos + 1
    print("ada {} Hippo" . format(hippos))
    answer = input("tambahkan hippo ? (y/n)")

tambahHippo()

