# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2c2UDOUYy8SxQ5p_zVOErrDHBwPX0hC
"""

for i in range (10):
  print("saya tidak akan mengulanginya lagi")

lanjut = True
while(lanjut):
  option = input("Lanjut atau tidak?  (y/n)")
  if(option == 'n'):
    lanjut = False
    print("Program Berhenti")

price  = 25000
uang = 10000
if price == uang:
  print ("uang pas")
elif price < uang:
  print("uang lebih")
else:
  print("uang tidak cukup")

username = "universitas"
password = "pertamina"
kesempatan = 3

while(kesempatan > 0):
  username_user = input("Masukkan username : ")
  password_user = input("Masukkan password : ")

  if(username == username_user and password == password_user):
    print("Login Berhasil")
    break
  else:
    kesempatan -= 1
    print("Kesempatan {} kali lagi ".format (kesempatan))

x = 5
print(type(x))

y = 0.5
print(type(y))

mobil = "Hijau"
print(type(mobil))

uang = 25000
if uang >= 25000:
  print("uang cukup")
else:
  print("uang tidak cukup")

def perkalian(angka1, angka2):
  return angka1*angka2
hasil = perkalian(1,1)
print(hasil)

def tambahHippo():
  hippos = 0
  answer = 'y'
  while answer == 'y':
    hippos = hippos + 1
    print("Ada {} Hippo".format(hippos))
    answer = input ("Tambahkan Hippo? (y/n)")

tambahHippo()